### ISSUE TITLE
Integration problem when installing on ubuntu 16

### ISSUE THREAD

**Issue by revvie** [bitbackofen/Rss-Atom-Feed-Integration-for-Mattermost#37]
Hi, i am getting this error when running feedfetcher.py, or when using docker image and running docker-compose up: 

Traceback (most recent call last):
  File "./feedfetcher.py", line 166, in <module>
    httpd = HTTPServer((integration_listening_addr, integration_listening_port), RSSManagementRequestHandler)
  File "/usr/lib/python2.7/SocketServer.py", line 417, in __init__
    self.server_bind()
  File "/usr/lib/python2.7/BaseHTTPServer.py", line 108, in server_bind
    SocketServer.TCPServer.server_bind(self)
  File "/usr/lib/python2.7/SocketServer.py", line 431, in server_bind
    self.socket.bind(self.server_address)
  File "/usr/lib/python2.7/socket.py", line 228, in meth
    return getattr(self._sock,name)(*args)
socket.error: [Errno 13] Permission denied

**Comment by dbanck** [comment]
What's your `integration_listening_port`? You can't bind ports below 1024 without being root.

**Comment by revvie** [comment]
The port was set to 80, i have changed it to 8080. I'm now successfully running the script, but it is still not posting to the mattermost channel.

**Comment by Okhoshi** [comment]
Could you share your configuration with us ?

**Comment by revvie** [comment]
This is what settings.py looks like:

# Paste the Mattermost webhook URL you created here
# See also: https://docs.mattermost.com/developer/webhooks-incoming.html
mattermost_webhook_url = 'my webhook url '

# Paste the Mattermost integration Token you created here
# See also: https://docs.mattermost.com/developer/slash-commands.html
mattermost_integration_token = 'my token string'

# Set the delay between feed pulls to your needs. 5 minutes should be okay.
delay_between_pulls = 60 * 5

# Trust only signed SSL certificate?
verify_cert = False

# Deactivate logging for debug purposes
silent_mode = True

# Name of the user that responds to integration commands
integration_bot_name = 'RSS-Bot'

# Image URL for the user that responds to integration commands
integration_bot_img = ''

# Address integration bot must listen to ('' for every host)
integration_listening_addr = ''

# Port integration bot must listen to
integration_listening_port = 8080

# Don't publish the article fetched on the first run (avoid spamming when rebooting a lot the bot)
skip_init_article = True

# Default settings for the feeds
default_show_name = True
default_show_title = True
default_show_description = True
default_show_url = True
default_channel = ''

# Your feeds come here:
# RssFeed('Feed name', 'Feed URL', 'Image URL', 'Mattermost username', 'Mattermost channel',
# show name, show title, show description, show url)
#
# show name, show title, show description, show url can be True or False; at least one of them should be True
# show description (longer text or full article) seems not to work with every feed.
# Set to False it if a feed doesnt´t work.
# Hint: Channel overriding seems not to work with the channel 'Town Square'
feeds = [RssFeed('Heise News', 'http://heise.de.feedsportal.com/c/35207/f/653902/index.rss',
                 'http://elpatron.cepheus.uberspace.de/rss/rss3.png', 'revvie', 'rss',
                 True, True, True, True),
         RssFeed('t3n', 'https://feeds2.feedburner.com/aktuell/feeds/rss/',
                 'http://elpatron.cepheus.uberspace.de/rss/rss3.png', 'revvie', 'rss',
                 True, True, False, True),
         RssFeed('Toms Hardware', 'http://www.tomshardware.com/articles.xml', '', 'revvie', 'rss',
                 True, True, True, True),
         RssFeed('Mattermost Forum', 'http://forum.mattermost.org/latest.rss',
                 'http://www.mattermost.org/wp-content/uploads/2015/08/logomark.png', 'RSS-Bot', 'rss',
                 True, True, True, True)
]

This is what the docker config file looks like:

version: '2’
services:
mattermost-rss:
build: .
environment:
MATTERMOST_HOOK_URL: 'my mattermost hook url’
MATTERMOST_CMD_TOKEN: 'my mattermost token’
RSS_SILENT_MODE: 'True’
RSS_SHOW_NAME: 'False’
RSS_SHOW_TITLE: 'True’
RSS_SHOW_DESCR: 'True’
RSS_SHOW_URL: 'False’
RSS_VERIFY_SSL_CERT: 'False’
RSS_SKIP_INIT_ARTICLE: 'False’
INTEGRATION_BOT_NAME: 'revvie’
INTEGRATION_BOT_IMG: ''
INTEGRATION_LISTENING_ADDR: ''
INTEGRATION_LISTENING_PORT: '8080’
MATTERMOST_CHANNEL: 'rss’
env_file:
- feeds.env
volumes:
- ./feeds.env:/code/feeds.env:rw

The bot is running on the same machine as the Mattermost install.

**Comment by Okhoshi** [comment]
Why don't you use the provided Docker image ?
Also, if you use Docker, the settings.py file is normally ignored (and superseded by the settings.py.docker).

To provide an initial set of feeds, you should then use the feeds.env file.

Are the bot and Mattermost able to reach each other ?

**Comment by revvie** [comment]
I have tried using both.
The problem with the docker image is that it doesn't display the feeds when running docker-compose up:

`mattermost-rss_1`  | 2018-01-24 13:30:38,898 - [TheLoop] Feed is empty. Waiting f                                                                                        or good news...
mattermost-rss_1  | 2018-01-24 13:30:38,900 - [CommitStrip] Feed is empty. Waiti                                                                                        ng for good news...
mattermost-rss_1  | 2018-01-24 13:30:38,900 - [BBC] Feed is empty. Waiting for g                                                                                        ood `news...`

I'm not sure they can reach each other, could you specify how to check this ?

**Comment by Okhoshi** [comment]
I suppose that both Mattermost and Bot are running in Docker?

If so, you can enter each container with `docker exec -ti <container_id> ping <other_container_ip>` for instance.

The Docker image should post the last published article when it starts by default.

**Comment by revvie** [comment]
Only the rss bot is running in Docker.

**Comment by tsia** [comment]
this might be a completely stupid comment (and probably also too late) but have you tried to set `skip_init_article = False` for testing?

**Comment by Okhoshi** [comment]
@revvie No it won't post the "Feed is empty" string to the channel. It's just an indication that nothing has been found.

But @tsia gave a good reason why you don't see anything at startup. Could you check the value of `skip_init_article` ?

**Comment by megos** [comment]
@revvie Same issue.  
I resolved this issue by fix `feeds.env`. Remove single quotes.

### OK
`RSS_FEED_CommitStrip=https://www.commitstrip.com/en/feed/;https://www.commitstrip.com/wp-content/themes/krds_blog/images/logo_small.png`

### NG
`RSS_FEED_CommitStrip='https://www.commitstrip.com/en/feed/;https://www.commitstrip.com/wp-content/themes/krds_blog/images/logo_small.png'`
