### ISSUE TITLE
python3?

### ISSUE THREAD

**Issue by ChrisFernandez** [bitbackofen/Rss-Atom-Feed-Integration-for-Mattermost#7]
Im having issues running this.. all my servers come with python3 by default
and python2 the old one on the side... but you have to type python2 instead of python
but im getting this:
sudo pip install -r requirements.txt

all my stuff is installed:
Requirement already satisfied (use --upgrade to upgrade): requests==2.2.1 in /home/rek2/.local/lib/python2.7/site-packages (from -r requirements.txt (line 1))
Requirement already satisfied (use --upgrade to upgrade): feedparser==5.2.1 in /home/rek2/.local/lib/python2.7/site-packages (from -r requirements.txt (line 2))
Requirement already satisfied (use --upgrade to upgrade): html2text==2015.6.21 in /home/rek2/.local/lib/python2.7/site-packages (from -r requirements.txt (line 3))
Cleaning up...

and command:
 python2 feedfetcher.py 
Traceback (most recent call last):
  File "feedfetcher.py", line 13, in <module>
    import requests
  File "/home/rek2/.local/lib/python2.7/site-packages/requests/__init__.py", line 53, in <module>
    from .packages.urllib3.contrib import pyopenssl
  File "/home/rek2/.local/lib/python2.7/site-packages/requests/packages/urllib3/contrib/pyopenssl.py", line 62, in <module>
    ssl.PROTOCOL_SSLv3: OpenSSL.SSL.SSLv3_METHOD,
AttributeError: 'module' object has no attribute 'PROTOCOL_SSLv3'

whats going on? Im a ruby/c/c++ person rarely run python stuff.

**Comment by ChrisFernandez** [comment]
hello found the solution: http://stackoverflow.com/questions/28987891/patch-pyopenssl-for-sslv3-issue
